name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" # Every 24 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#7209b7&color_dots=#ebedf0,#ffccd5,#ff85a1,#ff477e,#ff0a54
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#ff007f&color_dots=#161b22,#0a2e5c,#0077b6,#00b4d8,#90e0ef
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
